### PR TITLE
Testing pre-commit CI tool and small code formatting

### PR DESCRIPTION
**Pull request by Lolomgrofl**

### CODE REVIEW

**Comment by grski** [comment]
this looks quite interesting, however I'm wondering if in real-use cases, won't complain about compliance/privacy compared to plain github actions 🤔 what's your experience/thoughts on this?

**Comment by grski** [comment]
``` yaml
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
      ```
      this looks promising
      https://pre-commit.ci/lite.html

**Comment by Lolomgrofl** [comment]
> this looks quite interesting, however I'm wondering if in real-use cases, won't complain about compliance/privacy compared to plain github actions 🤔 what's your experience/thoughts on this?

**Comment by Lolomgrofl** [comment]
> > this looks quite interesting, however I'm wondering if in real-use cases, won't complain about compliance/privacy compared to plain github actions 🤔 what's your experience/thoughts on this?

Actually I saw that it's used on couple of places, it's easy to setup really basically since I already created this `pre-commit-config` file on repo basis, I can just reuse the same code as put it as CI. Which makes sense for these things like, linters etc IMHO.

**Comment by Lolomgrofl** [comment]
> 

Yep, that's the CI that I'm using here. It's less code when you put it inside pre-commit-config file

**Comment by grski** [comment]
in the example above it's show how to use it as a github action step, so it mitigates my enterprise-unneeded-paranoid worry, good finding, cool, thakns for sharing

**Pull request merged**
